### ISSUE TITLE
Seemingly out-of-bound trajectory?

### ISSUE THREAD

**Issue by soraxas** [dfki-ric/ugv_nav4d#12]
Thanks for the additional build instruction, I was able run the application.

By following the given instructions, the result trajectory seems to go out-of-bound (where it penetrates the bottom of the floor at the goal) and has some redundant paths. (circled in red)

What are those? Is that some bug?

![image](https://github.com/user-attachments/assets/982c7e78-c92b-46a1-af94-437242e6c43d)

If you look closely to the image in the README.md, it also seems to have trajectory on void space (no floor)

![image](https://github.com/user-attachments/assets/0d82161a-0ba6-430a-b288-6a7f929a345b)

**Comment by soraxas** [comment]
It seems like perhaps those are some visual artifacts of the solution trajectory projected to the ground

**Comment by haider8645** [comment]
It is just the 2D version of the 3D Trajectory. You can disable the visualization on the right side (drop-downs) :)

**Comment by soraxas** [comment]
I see, perhaps default to False (while keeping your option to toggle it) would be good.

**Comment by haider8645** [comment]
Disabled Trajectory 2D by default and also added names for the visualization.

![image](https://github.com/user-attachments/assets/0b76478d-97db-4b5e-b6b3-e14eea95afe8)

**Comment by soraxas** [comment]
Looks good to me!
