### ISSUE TITLE
Example Case

### ISSUE THREAD

**Issue by haider8645** [dfki-ric/ugv_nav4d#16]
Hello @OlgerSiebinga,

I added an [example case in the documentation](https://github.com/dfki-ric/ugv_nav4d/tree/example_case?tab=readme-ov-file#ros-2-humble-test-environment-with-gazebo-fortress). It shows how to use ugv_nav4d in ros2 within a test environment. The repositories for the test case are not yet published. The example should give a good starting point for users.

I will let you know after publishing the ros2 wrapper so that you can test it.

**Comment by haider8645** [comment]
@soraxas FYI

**Comment by haider8645** [comment]
The repositories are published.

https://github.com/dfki-ric/ugv_nav4d_ros2
https://github.com/dfki-ric/ros2_humble_gazebo_sim

**Comment by soraxas** [comment]
Nice!

**Comment by OlgerSiebinga** [comment]
HI @haider8645,

I tried to run the example case in ros on a fresh installation today, but I got stuck at step 5 of the readme instructions: the ros2 build. It seems there is a dependency missing in the instruction because I get the following error message:

```
$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
Starting >>> lidarslam_msgs
Starting >>> ndt_omp_ros2
Starting >>> ugv_nav4d_ros2
Finished <<< ndt_omp_ros2 [0.25s]                                       
--- stderr: ugv_nav4d_ros2
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:19 (pkg_check_modules)


---
Failed   <<< ugv_nav4d_ros2 [0.25s, exited with code 1]
Aborted  <<< lidarslam_msgs [0.34s]                                

Summary: 1 package finished [0.61s]
  1 package failed: ugv_nav4d_ros2
  1 package aborted: lidarslam_msgs
  1 package had stderr output: ugv_nav4d_ros2
  3 packages not processed
```

**Comment by OlgerSiebinga** [comment]
turns out I had to source the `env` of the original ugv_nav4d installation to make it visible to Ros. This is mentioned in the wrapper readme but not in the example instructions. Might be nice to add it there.

**Comment by OlgerSiebinga** [comment]
I ran into another minor thing, I had to manually install `ros-humble-ros-ign` to get the launch script to run. After that, I managed to  get the launch script to run, but returns the following error:

```
[Err] [Server.cc:139] Error Code 13: [/sdf/world[@name="gz"]/include[0]/uri:/home/localadmin/ros2_ws/ros2_humble_gazebo_sim/simulation/models/cave_circuit.sdf:L16]: Msg: Unable to find uri[model://COSTAR_HUSKY_SENSOR_CONFIG_1]
```
Looks like I'm missing a config file. Or is this something I can fix on my side?

**Comment by haider8645** [comment]
Do you get the same error even after sourcing the following:

```
export IGN_GAZEBO_RESOURCE_PATH=/home/localadmin/ros2_ws/ros2_humble_gazebo_sim/resource:$IGN_GAZEBO_RESOURCE_PATH
```

**Comment by OlgerSiebinga** [comment]
thanks, I forgot that one!
The list of `source`s and `export`s to run the launch command is quite long. It might be nice to provide an extensive list because now I had to trace it back from between the build commands in the example (I ran all the builds yesterday and just wanted to launch the example today). Anyway, just a suggestion.

**Comment by haider8645** [comment]
Yes, I agree with you. It would be a challenge for anyone to go through all the commands and text. Hmm, I will find a way to make it user friendly. Thanks for the heads up!

**Comment by haider8645** [comment]
I have updated the readme with the hint to source ugv_nav4d before building the ros2 workspace. I will close this for now so that a starting example case is available for users and later update the readme to improve overall usability
