### ISSUE TITLE
Tracking PLY file in repo

### ISSUE THREAD

**Issue by soraxas** [dfki-ric/ugv_nav4d#3]
Should the PLY files be tracked inside this source repo?

It contains > 100 MB just to clone the repo.

```sh
$ du -h -d1
36M	./.git
252K	./src
3.0M	./doc
2.0M	./paper
28K	./source_dependencies
119M	./test_data
160M	.
```

(part of https://github.com/openjournals/joss-reviews/issues/6983)

**Comment by haider8645** [comment]
Good point, I guess it would be better to move the ply file(s) to a external storage location. Do you have any recommendation or am I free to choose any?

**Comment by soraxas** [comment]
Nice, and it seems you've removed the old blob data by cleaning the repo 👍
