### ISSUE TITLE
Functionality documentation

### ISSUE THREAD

**Issue by soraxas** [dfki-ric/ugv_nav4d#4]
>  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

It seems the repo has a `Doxyfile.in` file (https://github.com/dfki-ric/ugv_nav4d/blob/main/Doxyfile.in), but there's no generated API documentation to be found?

**Comment by haider8645** [comment]
Running ```make doc```inside the build folder should now generate the doxygen documentation. Also added a section to the README.md [here](https://github.com/dfki-ric/ugv_nav4d?tab=readme-ov-file#generate-api-documentation)

**Comment by planthaber** [comment]
The "make doc" target is only generated whan doxygen is installed

**Comment by soraxas** [comment]
Can you add a link to the hosted built doc as API documentation to close this?

It's at the `gh-pages` branch https://github.com/dfki-ric/ugv_nav4d/tree/gh-pages

**Comment by planthaber** [comment]
Doxygen doc is now availabe here: https://dfki-ric.github.io/ugv_nav4d/

Also added the link as Link in the about field of the repo.

**Comment by soraxas** [comment]
Looks good to me
