### ISSUE TITLE
Build system depends on `Rock` 

### ISSUE THREAD

**Issue by soraxas** [dfki-ric/ugv_nav4d#6]
It seems the build system depends on `rock`, a build system macro developed by `dfki.de`:

https://github.com/dfki-ric/ugv_nav4d/blob/86650761370d2ed10e6fc49aa6ff797c18182a13/CMakeLists.txt#L28-L31

However, its not part of the install target in the `source_dependencies` scripts.

The Readme file contains the following text:

```
Compiling inside a ROCK environment
See the manifest.xml for an up to date list of dependencies.

Buidling inside ROCK works as usual. The package can be found in the backbone package set: https://git.hb.dfki.de/sw-backbone/package_sets
```

However, the gitlab link https://git.hb.dfki.de/sw-backbone/package_sets is private and requires login?

(part of https://github.com/openjournals/joss-reviews/issues/6983)

**Comment by haider8645** [comment]
We use the library as part of the ROCK robotics framework developed and used at DFKI. However, from the open source user community view, we use this [CMakeLists](https://github.com/dfki-ric/ugv_nav4d/blob/main/source_dependencies/CMakeLists.txt) which together with installation steps should automatically setup and install all the dependencies.

**Comment by OlgerSiebinga** [comment]
If I try to use the automatic installation, I'm still getting an error that ROCK cannot be installed:

`CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  build/install/share/rock/cmake/Rock.cmake:322 (pkg_check_modules)
  build/install/share/rock/cmake/Rock.cmake:520 (rock_find_pkgconfig)
  build/install/share/rock/cmake/Rock.cmake:944 (rock_target_definition)
  build/install/share/rock/cmake/Rock.cmake:1042 (rock_library_common)
  src/CMakeLists.txt:55 (rock_library)
`

I followed the steps in the README file for automatic installation:

` cd ugv_nav4d
   mkdir build && cd build
   cmake -DINSTALL_DEPS=ON -DCMAKE_INSTALL_PREFIX=./install ..
   make -j install
`

**Comment by haider8645** [comment]
Which OS are you using for the build?

**Comment by OlgerSiebinga** [comment]
Ubuntu 22.04.4

**Comment by haider8645** [comment]
Hmm, that is very strange. I followed the same steps on ```Ubuntu 22.04.2 LTS``` and it worked for me.

**Comment by OlgerSiebinga** [comment]
It is strange indeed. I deleted everything and started over and ran into another issue ( https://github.com/dfki-ric/ugv_nav4d/issues/9). I fixed that one, and the Rock error did not show again. But I really don't understand why it's gone now.

**Comment by soraxas** [comment]
My main system is Arch, and I have numerous issues with getting the correct dependencies as listed in [install_os_dependencies.bash](https://github.com/dfki-ric/ugv_nav4d/blob/main/source_dependencies/install_os_dependencies.bash). (hence the delayed review). I wasn't quite able to get the correct listed of dependencies as the cmake expects certain versions of packages and has version incompatibilities across packages (and the `apt-get ...` commands doesn't quite specify the needed versions). 

In the end, I've given up and ended up using a fresh copy of container with Ubuntu 22 that can run the `apt-get` commands. I can however confirm that a fresh ubuntu 22 did not encounter the issue noted by @OlgerSiebinga, and installs without issues. (so perhaps the noted issue is due to conflicts on existing systems, like qt as noted in another issues).

**Comment by soraxas** [comment]
Since I've verified that the install script works on a fresh Ubuntu 22, and it seems it works for @OlgerSiebinga after removing his previous QT installation, let's close this .
