### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by soraxas** [dfki-ric/ugv_nav4d#7]
Needs the following as part of the documentation

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

(part of https://github.com/openjournals/joss-reviews/issues/6983)

**Comment by haider8645** [comment]
Added a CONTRIBUTING.md file to the repo

**Comment by soraxas** [comment]
Looks good
