### ISSUE TITLE
Unit Tests and CI

### ISSUE THREAD

**Issue by soraxas** [dfki-ric/ugv_nav4d#8]
> Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

In https://github.com/dfki-ric/ugv_nav4d/blob/main/src/test/test_ugv_nav4d.cpp there contains a few google test function.
But I wouldn't call it unit testing as it's only setting up 1 scenario and tested:
- setting up grid resolution
- valid / invalid start/end states
- tested it can finishes (finding solution) for 1 particular planning request

Can we have some more structured unit testing in the traditional sense?

(part of https://github.com/openjournals/joss-reviews/issues/6983)

**Comment by soraxas** [comment]
The CI file in https://github.com/dfki-ric/ugv_nav4d/blob/main/.gitlab-ci.yml is using Gitlab format. 

Presumably, it's from `dfki-ric`'s private gitlab instance? If this public instance will be in Github, you should use github action instead

https://docs.github.com/en/actions

**Comment by haider8645** [comment]
Build CI: [Added github actions based build CI](https://github.com/dfki-ric/ugv_nav4d/actions) 

Unit Testing: The current tests test basic functionality of the planner. If you want something else then can you point me to an example implementation on another library? Thanks!

**Comment by soraxas** [comment]
Some C++ examples:

https://github.com/tbrown122387/pf/tree/master/test

https://github.com/kdm9/libqcpp/tree/master/src/tests

Both of these are JOSS C++ libraries

**Comment by planthaber** [comment]
The tests are located here: https://github.com/dfki-ric/ugv_nav4d/tree/main/src/test

@haider8645: Add the TESTS_ENABLED=ON cmake option, ply download and running the tests in the github action.

**Comment by soraxas** [comment]
Thanks @planthaber but that's what I've already linked in the OP.

As mentioned, some form of unit test would be better (there's only one file in the folder, contains only integration test, i.e., end-to-end test).

E.g. From a quick glance, (non-exhaustive list) your repo has things like Dijkstra algorithm, EnvironmentXYZTheta, compute motion, etc. These are individual item can be use some form tests.

**Comment by haider8645** [comment]
> ply download

uploaded the ply files to zenodo. They just need to be added to your organization by the curators and then can remove the test files from repo and update docu and action

**Comment by haider8645** [comment]
@soraxas I am working on the unit tests.

**Comment by soraxas** [comment]
Will review, thanks

**Comment by soraxas** [comment]
Good to close this when #18 is merged

**Comment by haider8645** [comment]
Thank you! closing this.
